version: "3.7"

services:
  backend:
    image: deployments-backend
    container_name: deployments_backend
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src
    environment:
      DB_HOST: db
    ports:
      - 3000:3000
    command: sh -c "rails db:setup && rails s -b 0.0.0.0"
  db:
    image: postgres:11.3-alpine
    container_name: deployments_db
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: deployment_dev
