version: "3.7"

services:
  frontend:
    image: deployments-frontend
    container_name: deployments_frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src
      - /usr/src/node_modules
    ports:
      - 8080:8080
    command: npm run serve
  backend:
    image: deployments-backend
    container_name: deployments_backend
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src
    environment:
      DB_HOST: db
    ports:
      - 3000:3000
    command: sh -c "rm -f tmp/pids/* && rails db:setup && rails s -b 0.0.0.0"
  db:
    image: postgres:11.4-alpine
    container_name: deployments_db
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: deployment_dev
