require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'

Naming/MethodParameterName:
  Exclude:
    - 'app/controllers/graphql_controller.rb'

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
  Max: 50

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'app/controllers/graphql_controller.rb'

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Include:
    - 'app/**/*.rb'
