version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:11.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: backend_test
    steps:
      - checkout
      - run: sudo apt install -y postgresql-client || true
      - run:
          name: install gems
          command: bundle install --with development test --without production --jobs 4 --retry 3
          working_directory: backend
      - run:
          name: setup db
          command: RAILS_ENV=test rails db:create db:migrate
          working_directory: backend
      - run:
          name: rspec
          command: rspec
          working_directory: backend
