version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:11.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: backend_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - deployments-{{ checksum "backend/Gemfile.lock" }}
            - deployments-
      - run: sudo apt install -y postgresql-client || true
      - run:
          name: install gems
          command: >
            gem install bundler --conservative &&
            bundle check --path=vendor/bundle ||
            bundle install --with development test --without production
            --path=vendor/bundle --jobs 4 --retry 3
          working_directory: backend
      - save_cache:
          key: deployments-{{ checksum "backend/Gemfile.lock" }}
          paths:
            - backend/vendor/bundle
      - run:
          name: setup db
          command: RAILS_ENV=test bundle exec rails db:create db:migrate
          working_directory: backend
      - run:
          name: rspec
          command: bundle exec rspec
          working_directory: backend
