version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run: ./script/cicrleci-setup.sh
      - run:
        name: rspec
        command: rspec
        working_directory: backend
