version: 2.1
jobs:
  backend:
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:11.4-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: backend_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - deployments-gems-{{ checksum "backend/Gemfile.lock" }}
            - deployments-gems-
      - run: sudo apt install -y postgresql-client || true
      - run:
          name: install gems
          command: >
            gem install bundler --conservative &&
            bundle check --path=vendor/bundle ||
            bundle install --with development test --without production
            --path=vendor/bundle --jobs 4 --retry 3
          working_directory: backend
      - save_cache:
          key: deployments-gems-{{ checksum "backend/Gemfile.lock" }}
          paths:
            - backend/vendor/bundle
      - run:
          name: rubocop
          command: bundle exec rubocop
          working_directory: backend
      - run:
          name: setup db
          command: RAILS_ENV=test bundle exec rails db:create db:migrate
          working_directory: backend
      - run: mkdir ~/rspec
      - run:
          name: rspec
          command: bundle exec rspec -f d -f RspecJunitFormatter -o ~/rspec/rspec.xml
          working_directory: backend
      - store_test_results:
          path: ~/rspec
  frontend:
    docker:
      - image: circleci/node:12.4.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - deployments-npms-{{ checksum "frontend/package-lock.json" }}
            - deployments-npms-
      - run:
          name: install npms
          command: npm ci
          working_directory: frontend
      - save_cache:
          key: deployments-npms-{{ checksum "frontend/package-lock.json" }}
          paths:
            - backend/vendor/bundle
      - run:
          name: lint
          command: npm run lint
          working_directory: frontend
  build-backend:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - setup_remote_docker # Reminder: paid feature docker_layer_caching: true
      - restore_cache:
          keys:
            - docker-cache-gems-{{ .Branch }}
      - restore_cache:
          keys:
            - docker-cache-backend-{{ .Branch }}
      - run: |
          mkdir -p caches
          docker load < caches/gems.tar || true
          docker build -t gems --target gems --cache-from gems backend
          docker save gems > caches/gems.tar

          docker load < caches/backend.tar || true
          docker build -t backend --target production --cache-from gems --cache-from backend backend
          docker save backend > caches/backend.tar

          docker tag backend joinez/deployments-backend
          docker login -u $HUB_USER -p $HUB_PASSWORD
          docker push joinez/deployments-backend
      - save_cache:
          key: docker-cache-gems-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - caches/gems.tar
      - save_cache:
          key: docker-cache-backend-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - caches/backend.tar
  build-frontend:
    docker:
      - image: circleci/node:12.4.0
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - docker-cache-npms-{{ .Branch }}
      - restore_cache:
          keys:
            - docker-cache-frontend-{{ .Branch }}
      - run: |
          mkdir -p caches
          docker load < caches/npms.tar || true
          docker build -t npms --target npms --cache-from npms frontend
          docker save npms > caches/npms.tar

          docker load < caches/frontend.tar || true
          docker build -t frontend --target production --cache-from npms --cache-from frontend frontend
          docker save frontend > caches/frontend.tar

          docker tag frontend joinez/deployments-frontend
          docker login -u $HUB_USER -p $HUB_PASSWORD
          docker push joinez/deployments-frontend
      - save_cache:
          key: docker-cache-npms-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - caches/npms.tar
      - save_cache:
          key: docker-cache-frontend-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - caches/frontend.tar

workflows:
  version: 2
  test:
    jobs:
      - backend
      - frontend
      - build-backend:
          requires:
            - backend
            - frontend
          context: docker_hub
      - build-frontend:
          requires:
            - backend
            - frontend
          context: docker_hub
